//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Super_Paper_Mario_Randomizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Super_Paper_Mario_Randomizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error extracting the ISO..
        /// </summary>
        internal static string err_extract_failed {
            get {
                return ResourceManager.GetString("err_extract_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder will be overwritten. Continue?.
        /// </summary>
        internal static string folder_will_be_overwritten {
            get {
                return ResourceManager.GetString("folder_will_be_overwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder exists.
        /// </summary>
        internal static string folder_will_be_overwritten_title {
            get {
                return ResourceManager.GetString("folder_will_be_overwritten_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO files (*.iso)|*.iso|WBFS files (*.wbfs)|*.wbfs.
        /// </summary>
        internal static string isoselect_filter {
            get {
                return ResourceManager.GetString("isoselect_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading stages....
        /// </summary>
        internal static string loading_stages {
            get {
                return ResourceManager.GetString("loading_stages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This does not seem to be a Super Paper Mario ISO..
        /// </summary>
        internal static string not_spm_iso {
            get {
                return ResourceManager.GetString("not_spm_iso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory to extract this ISO to....
        /// </summary>
        internal static string select_iso_extract_dir {
            get {
                return ResourceManager.GetString("select_iso_extract_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the &quot;setup&quot; folder extracted from a Super Paper Mario ISO..
        /// </summary>
        internal static string select_setup_folder {
            get {
                return ResourceManager.GetString("select_setup_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Super Paper Mario ISO....
        /// </summary>
        internal static string select_spm_iso {
            get {
                return ResourceManager.GetString("select_spm_iso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R8P.
        /// </summary>
        internal static string spm_titlecode {
            get {
                return ResourceManager.GetString("spm_titlecode", resourceCulture);
            }
        }
    }
}
